name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: bash dl.sh
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          timestamp=$(TZ=UTC date +%Y-%m-%dT%H:%M:%S)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
